name: CI

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "**"
  pull_request:

jobs:
  ci:
    uses: smallstep/workflows/.github/workflows/goCI.yml@main
    with:
      os-dependencies: "libpcsclite-dev"

